version: '3.3'

services:


        anime_database:
                image: pedro4064/anime-nas-db
                container_name: anime_database
                restart: always
                environment: 
                        - MYSQL_ROOT_PASSWORD=P3dr0mysql
                        - MYSQL_USER=root
                        - MYSQL_PASSWORD=P3dr0mysql
                        - MYSQL_DATABASE=Anime_NAS
                ports: 
                        - 3306:3306
                
        populate_db:
                image: pedro4064/anime_nas_populate_db
                container_name: populate_db                
                depends_on:
                        - anime_database
        
        anime_download:
                image: pedro4064/anime_nas_download
                container_name: anime_download
                restart: always
                depends_on:
                        - anime_database
                volumes:
                        - /media/pi/DISK/Animes:/animes
                # ports:
                #         - "5000:80"

        anime_web_app:
                image: pedro4064/anime_nas
                container_name: anime_web_app
                restart: always
                depends_on:
                        - anime_database

                volumes:
                        - /media/pi/DISK/Animes:/static/Animes
                        # - /home/pi/Documents/Docker/Anime-NAS:/scripts
                ports:
                        - "80:80"

        anime_daily_check:
                image: pedro4064/anime_nas_daily_check
                container_name: anime_daily_check
                restart: always
                volumes:
                        - /media/pi/DISK/Animes:/Animes
                        # - /home/pi/Documents/Docker/Anime-NAS:/scripts 

        season_anime_update:
                image: pedro4064/anime_nas_season_anime_update
                container_name: season_anime_update
                depends_on:
                        - anime_database
                ports: 
                        - "8080:8080"

        add_previously_downloaded_anime:
                image: pedro4064/add_previously_downloaded_anime
                container_name: add_previously_downloaded_anime
                depends_on: 
                        - anime_database